# Generated by Django 4.2.4 on 2024-02-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetCareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='petid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
